server:
  port: 8081
spring:
  application:
    name: "authservice"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null

logging:
  level:
    root: INFO
    co.com.authservice: DEBUG
adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: authservice_db
    schema: public
    username: ivan
    password: ivan123
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    r2dbc:
      enabled: true
      timeout: 30s
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

# SpringDoc OpenAPI Configuration
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true
  packages-to-scan: co.com.authservice.api

# JWT Configuration
jwt:
  secret: "mySecretKey123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890"
  expiration: 86400
